In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('credit_dataset.csv')
df.head()

Unnamed: 0       ID GENDER CAR REALITY  NO_OF_CHILD    INCOME  \
0           0  5008806      M   Y       Y            0  112500.0   
1           1  5008808      F   N       Y            0  270000.0   
2           2  5008809      F   N       Y            0  270000.0   
3           3  5008810      F   N       Y            0  270000.0   
4           4  5008811      F   N       Y            0  270000.0   

            INCOME_TYPE                 EDUCATION_TYPE           FAMILY_TYPE  \
0               Working  Secondary / secondary special               Married   
1  Commercial associate  Secondary / secondary special  Single / not married   
2  Commercial associate  Secondary / secondary special  Single / not married   
3  Commercial associate  Secondary / secondary special  Single / not married   
4  Commercial associate  Secondary / secondary special  Single / not married   

          HOUSE_TYPE  FLAG_MOBIL  WORK_PHONE  PHONE  E_MAIL  FAMILY SIZE  \
0  House / apartment           1           0      0       0          2.0   
1  House / apartment           1           0      1       1          1.0   
2  House / apartment           1           0      1       1          1.0   
3  House / apartment           1           0      1       1          1.0   
4  House / apartment           1           0      1       1          1.0   

   BEGIN_MONTH  AGE  YEARS_EMPLOYED  TARGET  
0           29   59               3       0  
1            4   52               8       0  
2           26   52               8       0  
3           26   52               8       0  
4           38   52               8       0

In [2]:
df.shape

(25134, 20)

In [3]:
df.isnull().count()

Unnamed: 0        25134
ID                25134
GENDER            25134
CAR               25134
REALITY           25134
NO_OF_CHILD       25134
INCOME            25134
INCOME_TYPE       25134
EDUCATION_TYPE    25134
FAMILY_TYPE       25134
HOUSE_TYPE        25134
FLAG_MOBIL        25134
WORK_PHONE        25134
PHONE             25134
E_MAIL            25134
FAMILY SIZE       25134
BEGIN_MONTH       25134
AGE               25134
YEARS_EMPLOYED    25134
TARGET            25134
dtype: int64

In [4]:
df['TARGET'].value_counts()

0    24712
1      422
Name: TARGET, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25134 entries, 0 to 25133
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      25134 non-null  int64  
 1   ID              25134 non-null  int64  
 2   GENDER          25134 non-null  object 
 3   CAR             25134 non-null  object 
 4   REALITY         25134 non-null  object 
 5   NO_OF_CHILD     25134 non-null  int64  
 6   INCOME          25134 non-null  float64
 7   INCOME_TYPE     25134 non-null  object 
 8   EDUCATION_TYPE  25134 non-null  object 
 9   FAMILY_TYPE     25134 non-null  object 
 10  HOUSE_TYPE      25134 non-null  object 
 11  FLAG_MOBIL      25134 non-null  int64  
 12  WORK_PHONE      25134 non-null  int64  
 13  PHONE           25134 non-null  int64  
 14  E_MAIL          25134 non-null  int64  
 15  FAMILY SIZE     25134 non-null  float64
 16  BEGIN_MONTH     25134 non-null  int64  
 17  AGE             25134 non-null 

In [6]:
floats=["INCOME","FAMILY SIZE","BEGIN_MONTH"]

for i in floats:
    df[i]=df[i].astype("int64")

In [7]:
from sklearn.preprocessing import LabelEncoder
labels=["GENDER","CAR","REALITY","INCOME_TYPE","EDUCATION_TYPE","HOUSE_TYPE","FAMILY_TYPE"]
label=LabelEncoder()

for i in labels:
    df[i]=label.fit_transform(df[i])

In [31]:
df.drop(('E_MAIL','REALITY'),axis=1,inplace=True)


KeyError: "[('E_MAIL', 'REALITY')] not found in axis"

In [9]:
df.columns.value_counts()

YEARS_EMPLOYED    1
BEGIN_MONTH       1
TARGET            1
PHONE             1
FAMILY_TYPE       1
HOUSE_TYPE        1
AGE               1
CAR               1
E_MAIL            1
EDUCATION_TYPE    1
WORK_PHONE        1
INCOME_TYPE       1
INCOME            1
FLAG_MOBIL        1
Unnamed: 0        1
REALITY           1
FAMILY SIZE       1
GENDER            1
NO_OF_CHILD       1
dtype: int64

In [10]:
x = df.drop('TARGET',axis = 1)
y = df.TARGET
y.head()

0    0
1    0
2    0
3    0
4    0
Name: TARGET, dtype: int64

In [11]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25134 entries, 0 to 25133
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      25134 non-null  int64
 1   GENDER          25134 non-null  int32
 2   CAR             25134 non-null  int32
 3   REALITY         25134 non-null  int32
 4   NO_OF_CHILD     25134 non-null  int64
 5   INCOME          25134 non-null  int64
 6   INCOME_TYPE     25134 non-null  int32
 7   EDUCATION_TYPE  25134 non-null  int32
 8   FAMILY_TYPE     25134 non-null  int32
 9   HOUSE_TYPE      25134 non-null  int32
 10  FLAG_MOBIL      25134 non-null  int64
 11  WORK_PHONE      25134 non-null  int64
 12  PHONE           25134 non-null  int64
 13  E_MAIL          25134 non-null  int64
 14  FAMILY SIZE     25134 non-null  int64
 15  BEGIN_MONTH     25134 non-null  int64
 16  AGE             25134 non-null  int64
 17  YEARS_EMPLOYED  25134 non-null  int64
dtypes: int32(7), int64(11)
mem

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size = 0.7)

In [14]:
y_train.value_counts()

0    17287
1      306
Name: TARGET, dtype: int64

In [15]:
#though 1 or yes value is less so it gives 50x more importance than each 0 value
class_weight = dict({0:1,1:50})

In [16]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 50})

In [17]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7415   10]
 [  42   74]]
0.9931043628166025
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      7425
           1       0.88      0.64      0.74       116

    accuracy                           0.99      7541
   macro avg       0.94      0.82      0.87      7541
weighted avg       0.99      0.99      0.99      7541



In [18]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7415   10]
 [  42   74]]
0.9931043628166025
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      7425
           1       0.88      0.64      0.74       116

    accuracy                           0.99      7541
   macro avg       0.94      0.82      0.87      7541
weighted avg       0.99      0.99      0.99      7541



# over sampleling

In [19]:
!pip install imblearn

In [20]:
from imblearn.over_sampling import RandomOverSampler

In [21]:
os = RandomOverSampler(0.8)
x_train_re,y_train_re = os.fit_resample(x_train,y_train)
print('pre{}'.format((y_train.value_counts())))
print('after{}'.format((y_train_re.value_counts())))

pre0    17287
1      306
Name: TARGET, dtype: int64
after0    17287
1    13829
Name: TARGET, dtype: int64


C:\Users\PIJUSH_DAS\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_re,y_train_re)

RandomForestClassifier()

In [23]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7409   16]
 [  36   80]]
0.9931043628166025
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7425
           1       0.83      0.69      0.75       116

    accuracy                           0.99      7541
   macro avg       0.91      0.84      0.88      7541
weighted avg       0.99      0.99      0.99      7541



In [24]:
from imblearn.combine import SMOTETomek

In [25]:
s = SMOTETomek(0.7)
x_train_r,y_train_r = s.fit_resample(x_train,y_train)
print('pre{}'.format((y_train.value_counts())))
print('after{}'.format((y_train_r.value_counts())))

C:\Users\PIJUSH_DAS\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.7 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


pre0    17287
1      306
Name: TARGET, dtype: int64
after0    17006
1    11819
Name: TARGET, dtype: int64


In [26]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_r,y_train_r)

RandomForestClassifier()

In [27]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7405   20]
 [  34   82]]
0.9928391460018565
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7425
           1       0.80      0.71      0.75       116

    accuracy                           0.99      7541
   macro avg       0.90      0.85      0.87      7541
weighted avg       0.99      0.99      0.99      7541

